export default [
  { "_id": "A101", "title": "Propulsion Assignment", "course": "RS101" },
  { "_id": "A102", "title": "Combustion Analysis", "course": "RS101" },
  { "_id": "A103", "title": "Nozzle Design Project", "course": "RS101" },
  { "_id": "A201", "title": "Aerodynamics Quiz", "course": "RS102" },
  { "_id": "A202", "title": "Flow Analysis", "course": "RS102" },
  { "_id": "A203", "title": "Heating Analysis", "course": "RS102" },
  { "_id": "A301", "title": "Structural Design Task", "course": "RS103" },
  { "_id": "A302", "title": "Orbital Calculations", "course": "RS103" },
  { "_id": "A303", "title": "Systems Engineering Exam", "course": "RS103" },
  
  { "_note": "The following assignments are gathered from courses.json descriptions" },

  { "_id": "A401", "title": "Organic Synthesis Lab", "course": "RS104" },
  { "_id": "A402", "title": "Reaction Mechanisms Quiz", "course": "RS104" },
  { "_id": "A403", "title": "Structure Determination Project", "course": "RS104" },
  { "_id": "A501", "title": "Coordination Complex Analysis", "course": "RS105" },
  { "_id": "A502", "title": "Solid State Chemistry Lab", "course": "RS105" },
  { "_id": "A503", "title": "Materials Properties Report", "course": "RS105" },
  { "_id": "A601", "title": "Thermodynamics Problem Set", "course": "RS106" },
  { "_id": "A602", "title": "Kinetics Experiment", "course": "RS106" },
  { "_id": "A603", "title": "Equilibrium Calculations", "course": "RS106" },
  { "_id": "A701", "title": "Elvish Translation Project", "course": "RS107" },
  { "_id": "A702", "title": "Script Analysis Assignment", "course": "RS107" },
  { "_id": "A703", "title": "Linguistic Evolution Essay", "course": "RS107" },
  { "_id": "A801", "title": "Diplomatic Strategy Analysis", "course": "RS108" },
  { "_id": "A802", "title": "Leadership Case Study", "course": "RS108" },
  { "_id": "A803", "title": "Inter-species Relations Report", "course": "RS108" },
  { "_id": "A901", "title": "Music Theory Fundamentals", "course": "RS109" },
  { "_id": "A902", "title": "Composition Analysis", "course": "RS109" },
  { "_id": "A903", "title": "Performance Practice Essay", "course": "RS109" },
  { "_id": "A1001", "title": "Democratic Theory Quiz", "course": "RS110" },
  { "_id": "A1002", "title": "Voting Systems Analysis", "course": "RS110" },
  { "_id": "A1003", "title": "Civic Engagement Project", "course": "RS110" },
  { "_id": "A1101", "title": "Educational Philosophy Essay", "course": "RS111" },
  { "_id": "A1102", "title": "Teaching Methods Evaluation", "course": "RS111" },
  { "_id": "A1103", "title": "Curriculum Design Project", "course": "RS111" },
  { "_id": "A1201", "title": "Christian Ethics Case Study", "course": "RS112" },
  { "_id": "A1202", "title": "Biblical Interpretation Assignment", "course": "RS112" },
  { "_id": "A1203", "title": "Theological Reflection Paper", "course": "RS112" },
  { "_id": "A1301", "title": "Sufi Poetry Analysis", "course": "RS113" },
  { "_id": "A1302", "title": "Islamic Philosophy Essay", "course": "RS113" },
  { "_id": "A1303", "title": "Mystical Practices Report", "course": "RS113" },
  { "_id": "A1401", "title": "Kalām Cosmological Arguments", "course": "RS114" },
  { "_id": "A1402", "title": "Islamic Ethics Analysis", "course": "RS114" },
  { "_id": "A1403", "title": "Comparative Theology Paper", "course": "RS114" },
  { "_id": "A1501", "title": "Ancient Chinese Philosophy Quiz", "course": "RS115" },
  { "_id": "A1502", "title": "Confucian Ethics Essay", "course": "RS115" },
  { "_id": "A1503", "title": "Daoist Principles Analysis", "course": "RS115" },
  { "_id": "A1601", "title": "Buddhist Meditation Practice", "course": "RS116" },
  { "_id": "A1602", "title": "Four Noble Truths Essay", "course": "RS116" },
  { "_id": "A1603", "title": "Mindfulness Application Project", "course": "RS116" },
  { "_id": "A1701", "title": "Vedantic Philosophy Analysis", "course": "RS117" },
  { "_id": "A1702", "title": "Yoga Philosophy Essay", "course": "RS117" },
  { "_id": "A1703", "title": "Hindu Ethics Case Study", "course": "RS117" },
  { "_id": "A1801", "title": "Ethical Dilemma Analysis", "course": "RS118" },
  { "_id": "A1802", "title": "Virtue Ethics Application", "course": "RS118" },
  { "_id": "A1803", "title": "Moral Philosophy Debate", "course": "RS118" },
  { "_id": "A1901", "title": "Existentialist Reading Response", "course": "RS119" },
  { "_id": "A1902", "title": "Authenticity and Freedom Essay", "course": "RS119" },
  { "_id": "A1903", "title": "Absurdism Analysis Project", "course": "RS119" },
  { "_id": "A2001", "title": "Phenomenology Method Application", "course": "RS120" },
  { "_id": "A2002", "title": "Consciousness Structure Analysis", "course": "RS120" },
  { "_id": "A2003", "title": "Intentionality Research Paper", "course": "RS120" },
  { "_id": "A2101", "title": "Process Philosophy Essay", "course": "RS121" },
  { "_id": "A2102", "title": "Whitehead's Metaphysics Analysis", "course": "RS121" },
  { "_id": "A2103", "title": "Creativity and Novelty Project", "course": "RS121" }
];
